### PR TITLE
chore: updates and pnpm config migration

### PR DESCRIPTION
**Pull request by TimMoser92**
- ran pnpm audit --fix with update first and then override to mend open vulnerabilities
- merged all applicable dependabot updates
- remove outdated pnpm override settings from package.json; background: pnpm v11 is ignoring these anyways: https://github.com/pnpm/pnpm/pull/10086

### CODE REVIEW

**Review by sebeweiss — APPROVED** [review]
Your PR looks good and my tests passed. After running `pnpm up` I noticed that bumping to `"@nestjs/swagger": "^11.4.3"` breaks the build in `src/app-init.ts`, `src/general/dto/esri-geometry.dto.ts`, and `src/general/dto/parameter.dto.ts` with:

```
error TS2307: Cannot find module '@nestjs/swagger/dist/interfaces/open-api-spec.interface' or its corresponding type declarations.

import { SchemaObject } from '@nestjs/swagger/dist/interfaces/open-api-spec.interface';
```

I pushed a proposed fix in https://github.com/geobakery/GeospatialAnalyzer/commit/1d51f1ed716b0cd2cab6ade817ee1badd36570a1. It's a workaround since `SchemaObject` isn't publicly exported, but it should be stable. Feel free to merge it in if you're good with the approach.

Just so you know, I'm back at work on 26.05.2026.

**Comment by TimMoser92** [comment]
> Your PR looks good and my tests passed. After running `pnpm up` I noticed that bumping to `"@nestjs/swagger": "^11.4.3"` breaks the build in `src/app-init.ts`, `src/general/dto/esri-geometry.dto.ts`, and `src/general/dto/parameter.dto.ts` with:
> 
> ```
> error TS2307: Cannot find module '@nestjs/swagger/dist/interfaces/open-api-spec.interface' or its corresponding type declarations.
> 
> import { SchemaObject } from '@nestjs/swagger/dist/interfaces/open-api-spec.interface';
> ```
> 
> I pushed a proposed fix in [1d51f1e](https://github.com/geobakery/GeospatialAnalyzer/commit/1d51f1ed716b0cd2cab6ade817ee1badd36570a1). It's a workaround since `SchemaObject` isn't publicly exported, but it should be stable. Feel free to merge it in if you're good with the approach.
> 
> Just so you know, I'm back at work on 26.05.2026.

Great work. Thank you! I added this commit here.
